config/routes.rb
Rails.application.routes.draw do

	root to: "pages#index"
	resources :food_trips

end

app/models/food_trip.rb
class FoodTrip < ActiveRecord::Base

	validates :food, presence: true
	validates :price, presence: true
	validates :store_location, presence: true
	validates :review, presence: true
	validates :rating_food, presence: true
	validates :rating_place, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/food_trips_controller.rb
class FoodTripsController < ApplicationController

	def index
		@food_trips = FoodTrip.all
	end
	
	def new
		@food_trip = FoodTrip.new
	end
	
	def create
		@food_trip = FoodTrip.new(food_trip_params)
		if @food_trip.save
			redirect_to food_trips_path
		else
			@message = @food_trip.errors.messages
			render :new
		end
	end

	def edit
		@food_trip = FoodTrip.find(params[:id])
	end
	
	def update
		@food_trip = FoodTrip.find(params[:id])
		if @food_trip.update(food_trip_params)
			redirect_to food_trips_path
		else
			@message = @food_trip.errors.messages
			render :edit
		end
	end

	def show
		@food_trip = FoodTrip.find(params[:id])
	end

	def destroy
		@food_trip = FoodTrip.find(params[:id])
		@food_trip.destroy
		redirect_to food_trips_path
	end

	def food_trip_params
		params.require(:food_trip).permit!
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
		@latest_food_trips = FoodTrip.last(5)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/food_trips/_food_trip.html.erb
<hr><br>
<h1><b><%= food_trip.food %></b></h1>
<h6><i>Updated: <%= food_trip.updated_at %></i></h6>

<div>
	<b>Price: </b><%= food_trip.price %>
</div>

<div>
	<b>Store Location: </b><%= food_trip.store_location %>
</div>

<div>
	<b>Date Visited: </b><%= food_trip.date_visited %>
</div>

<div>
	<b>Revew:</b><br><%= food_trip.review %>
</div>

<div>
	<b>Food Rating: </b><%= food_trip.rating_food %>
</div>

<div>
	<b>Store Rating: </b><%= food_trip.rating_place %>
</div>

<div>
	<b>Image: </b><br><img src="<%= food_trip.image %>">
</div>

<hr>

app/views/food_trips/_form.html.erb
<%= form_for food_trip do |f| %>
	<div>Food</div>
	<%= f.text_field :food %>
	<div>Price</div>
	<%= f.text_field :price %>
	<div>Store Location</div>
	<%= f.text_area :store_location %>
	<div>Date Visited</div>
	<%= f.date_select :date_visited %>
	<div>Food Review</div>
	<%= f.text_area :review %>
	<div>Rate the Food</div>
	<div><i>Rate from 1-10 (10 being the highest)</i></div>
	<%= f.text_field :rating_food %>
	<div>Rate the Place</div>
	<div><i>Rate from 1-10 (10 being the highest)</i></div>
	<%= f.text_field :rating_place %>
	<div>Food/Store Images</div>
	<%= f.text_field :image %>
	<hr>
	<%= f.submit "Save" %>
<% end %>

app/views/food_trips/about.html.erb
<hr><br>
<center>
<h5>About the Page</h5>
<div class="row">
	<div class="span9">
	<b>Welcome to my food trip blog!</b>
	<p>
	Hi, I am Kirk Jamison, a student living in the Philippines, who share the passion of eating food just like you. That's why you're here, right? Or maybe not. :) Thank you for visiting! It is my joy to share these food trips with you.
	</p><br><br>
<img src="kirk.jpg" height="20%" width="20%"/>
	</div>
</div>
</center>
<hr>

app/views/food_trips/edit.html.erb
<h1>Edit Food Trip Blog Post</h1>
<hr>
<%= render partial: "food_trips/form", locals: { food_trip: @food_trip } %>

app/views/food_trips/index.html.erb
<hr>
<br><br>
<div class="container">

      <div class="admin">
	<div class="span9">
        <h3><center>Food Trips</center></h3>
        <table class="table table-striped">
          <thead>
            <tr>
              <td>Name</td>
              <td>Price</td>
            </tr>
          </thead>
          <tbody>
          <% @food_trips.each do |food_trip| %>
            <tr>
              <td><%= food_trip.food %></td>
              <td><%= food_trip.price %></td>
	      <td><%= link_to "View Blog", food_trip_path(food_trip.id), method: :get %></td>
	      <td><%= link_to "Edit", edit_food_trip_path(food_trip.id) %></td>
	      <td><%= link_to "Delete", food_trip_path(food_trip.id), method: :delete, data: { confirm: "Are you sure?" } %></td>
           </tr>
			<% end %>          
	</tbody>          
        </table>
        <center><a href="/food_trips/new" class="btn btn-default">Create New Post</a></center>
	</div>
      </div>
</div><!-- /.container -->
<hr>

app/views/food_trips/new.html.erb
<hr>
<br><br>
<h3>New Food Trip Blog Post</h3>

<% if !@message.nil? %>
	<%= @message %>
<% end %>
<%= render partial: "food_trips/form", locals: { food_trip: @food_trip } %>

app/views/food_trips/show.html.erb
<hr><br>
	<h1><b><%= @food_trip.food %></b></h1>
	<h6><i>Updated: <%= @food_trip.updated_at %></i></h6>

	<div>
		<b>Price: </b><%= @food_trip.price %>
	</div>

	<div>
		<b>Store Location: </b><%= @food_trip.store_location %>
	</div>

	<div>
		<b>Date Visited: </b><%= @food_trip.date_visited %>
	</div>

	<div>
		<b>Revew:</b><br><%= @food_trip.review %>
	</div>

	<div>
		<b>Food Rating: </b><%= @food_trip.rating_food %>
	</div>

	<div>
		<b>Store Rating: </b><%= @food_trip.rating_place %>
	</div>

	<div>
		<b>Image: </b><br><img src="<%= @food_trip.image %>">
	</div>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Food Trip" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Food Trip</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "All Food Trip", "/food_trips"  %></li>
              <li><%= link_to "New Food Trip", "/food_trips/new"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">        
	<div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
	<div class="span1"></div>
          <div class="span2">
		<hr><hr><hr>
            <div class="well sidebar-nav">
              <h3>Navigation</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Links</li>
                <li><%= link_to "Home", "/"  %></li>
                <li><%= link_to "All Food Trips", "/food_trips"  %></li>
                <li><%= link_to "New Food Trip", "/food_trips/new"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

<hr>
<ul class="nav nav-list">
                <li class="nav-header">Links</li>
                <li><%= link_to "Home", "/"  %></li>
                <li><%= link_to "All Food Trips", "/food_trips"  %></li>
                <li><%= link_to "New Food Trip", "/food_trips/new"  %></li>
              </ul>
<hr>
      <footer>
        <p>&copy; Kirk Jamison, May 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/index.html.erb
<br>
<hr>
<div>
<center><h1><blink>Welcome to the Food Trip Blog!</blink></h1></center>
</div>
<br><br>
<div>
<h3>Latest Food Trips</h3>
<% @latest_food_trips.each do |f| %>
	<%= render partial: "food_trips/food_trip", locals: { food_trip: f } %>
<% end %>
</div>